version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests

  build:
    - executor: node/default
    - run:
        command: npm run build
        name: Build app
    - persist_to_workspace:
        root: ~/project
        paths:
          - .

  deploy:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true

workflows:
  test_my_app:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
